title: Basic Page (no sidebar)
pages: false

fields:
  headline: fields/headline
  text: defaultText

  ctaLine: fields/ctaLine
  ctaHelp: fields/ctaHelp
  cta: fields/cta
  ctaButton: fields/ctaButton
  ctaLink: fields/ctaLink
