title: Services page template
pages: false
files: true
icon: shopping-bag

fields:
  title: title
  headline: fields/headline
  heroImg: fields/heroImg
  socialImg: socialImg
  text: defaultText

  servicesHeadline:
    label: Services headline
  brandStrategyTitle:
    label: Brand strategy title
    width: 1/4
  brandstrategyList:
    label: Brand strategy list
    type: textarea
    toolbar: false
    width: 3/4
  brandAssetsTitle:
    label: Brand assets title
    width: 1/4
  brandAssetsList:
    label: Brand assets list
    type: textarea
    toolbar: false
    width: 3/4
  brandExperiencesTitle:
    label: Brand experiences title
    width: 1/4
  brandExperiencesList:
    label: Brand experiences list
    type: textarea
    toolbar: false
    width: 3/4

  quote: quote

  # ctaLine: fields/ctaLine
  # ctaHelp: fields/ctaHelp
  # cta: fields/cta
  # ctaButton: fields/ctaButton
  # ctaLink: fields/ctaLink
