title: Site
pages:
  - default
  - directory
  - parent

fields:
  keywords:
    label: Keywords
    type:  tags

  # doesn't work any more
  # title:
  #   label: Site title
  #   width: 1/3
  # description:
  #   extends: description
  #   width: 2/3
  # dropdownable:
  #   label: Pages with dropdown menus
  #   type: checkboxes
  #   options: visibleChildren
  #   width: 1/2
  # copyright:
  #   label: Copyright
  #   type:  markdown
  #
  # ctaLine: ctaLine
  # ctaHelp:
  #   extends: ctaHelp
  #   text: <h1>Default Call to Action</h1>
  # cta: cta
  # ctaButton: ctaButton
  # ctaLink: ctaLink
  #
  # imagesLine:
  #   type: line
  # imagesHeader:
  #   type: info
  #   text: >
  #     <h2>Default image filenames:</h2>
  #     <p>The CMS will search for an image matching the following filenames in a page's content folder if the corresponding filename is not provided for that page. <i>You probably don't want to change these.</i></p>
  # heroImg:
  #   label: hero
  #   width: 1/4
  # thumbImg:
  #   label: thumbnail
  #   width: 1/4
  # socialImg:
  #   label: social
  #   width: 1/4
  # nextImg:
  #   label: next
  #   width: 1/4
